### ISSUE TITLE
sorted-set

### ISSUE THREAD

**Issue by jmmk** [martinklepsch/custom-comparator-set#3]
I have a use case where I'm currently using a [priority map](https://github.com/tailrecursion/cljs-priority-map) - the key is `(:id my-map)` where `my-map` is `{:id id :priority priority}` and I can iterate over the results based on the priority.

The custom comparator set works well for replacing the use of a map, but I still need the values in order. Since sorted-set complements set in the standard library, would it make sense to have a sorted-set here as well?

**Comment by martinklepsch** [comment]
@jmmk sounds reasonable to me. I'd have to take a look at how that could be implemented but certainly sounds possible. 

Wonder what a constructor function could be named like. `sorted-set-by` exists and a sorted custom comparator set would need two parameters, one for `contains?` and one for sorting.

**Comment by jmmk** [comment]
It could be implemented in terms of [clojure priority-map](https://github.com/clojure/data.priority-map) and 
[cljs priority-map](https://github.com/tailrecursion/cljs-priority-map).

**Comment by jmmk** [comment]
This probably doesn't make sense. Since the data structure is about comparator-returned values, if there was a sorted version it should probably relate to that as well. 

I think I'd be better off storing the priority information in a separate place instead of trying to force everything into one, or just using functions to do the sorting instead of having a data structure that's too smart/customized.
