### ISSUE TITLE
Update/replace values

### ISSUE THREAD

**Issue by jmmk** [martinklepsch/custom-comparator-set#7]
One of the advantages to using a map of `{(comparator v) v}` is that you can update `v` with `assoc`. I realized I was actually relying on the buggy behavior of `conj` (#6) in cljs to accomplish the same thing.

Currently the only way to do this correctly with the ccset would be `(conj (disj ccset v) v)`. Would it make sense to have something like `(replace ccset v)` where the implementation could do the assoc on the underlying map? 

It seems sort of "out-of-bounds" for a set implementation so maybe it's better off as a helper function or maybe where I need it to be updatable I should use a map instead.

**Comment by martinklepsch** [comment]
I think since conj replaces values in regular sets I think it should do the same for ccsets. 

Maybe the implementation is wonky right now because of the stuff we discussed in #6 but it relatively easy to fix? 

In case I'm misunderstanding an example will probably clear things up :)

**Comment by jmmk** [comment]
For reference, let's look at the implementation of conj for PersistentHashSet in clj and cljs

# 

ClojureScript:

``` clojure
; src/main/cljs/cljs/core.cljs
ICollection
(-conj [coll o]
  (PersistentHashSet. meta (assoc hash-map o nil) nil))
```

# 

Clojure:

``` clojure
; src/clj/clojure/core.clj
(def
 ^{:arglists '([coll x] [coll x & xs])
   :doc "conj[oin]. Returns a new collection with the xs
    'added'. (conj nil item) returns (item).  The 'addition' may
    happen at different 'places' depending on the concrete type."
   :added "1.0"
   :static true}
 conj (fn ^:static conj
        ([] [])
        ([coll] coll)
        ([coll x] (clojure.lang.RT/conj coll x))
        ([coll x & xs]
         (if xs
           (recur (clojure.lang.RT/conj coll x) (first xs) (next xs))
           (clojure.lang.RT/conj coll x)))))
```

``` java
// src/jvm/clojure/lang/RT.java
static public IPersistentCollection conj(IPersistentCollection coll, Object x){
    if(coll == null)
        return new PersistentList(x);
    return coll.cons(x);
}
```

``` java
// src/jvm/clojure/lang/PersistentHashSet.java
public IPersistentSet cons(Object o){
    if(contains(o))
        return this;
    return new PersistentHashSet(meta(),impl.assoc(o,o));
}
```

# 

For hash-set, ClojureScript always runs the assoc, but Clojure checks if the element already exists in the set. 

For ccset, assuming `contains?` checks that `(comparator v)` already exists in the set and is not checking for value equality, then if ccset mirrored the hash-set implementation ClojureScript would always update the value and Clojure never would. Examples:

ClojureScript

``` clojure
;; ClojureScript always runs the assoc, so the value will be updated
(def ccset (custom-comparator-set :id {:id 1}))
(conj ccset {:id 1 :other 2}) ; data-map == {1 {:id 1 :other 2}}
(conj (conj ccset {:id 1 :other 2}) {:id 1 :other 3}) ; data-map == {1 {:id 1 :other 3}}
```

Clojure

``` clojure
;; Clojure checks for contains?, so the collection is returned as-is
(def ccset (custom-comparator-set :id {:id 1}))
(conj ccset {:id 1 :other 2}) ; data-map == {1 {:id 1}}
(conj (conj ccset {:id 1 :other 2}) {:id 1 :other 3}) ; data-map == {1 {:id 1}}
```

So I guess the answer to this affects how conj should be implemented to fix #6. The question being: Should `conj`ing a new value with the same "id" replace the old value or return the collection as-is?

**Comment by jmmk** [comment]
@martinklepsch any thoughts on this?

**Comment by martinklepsch** [comment]
> Should conjing a new value with the same "id" replace the old value or return the collection as-is?

That seems closest to sets and also most useful. If `conj` is implemented it should also be useful for something :) 

What do you think?

**Comment by jmmk** [comment]
I think that would give it slightly different semantics from a set, but as long as that's documented it's fine. If it fits your use-case (it definitely fits mine) and your idea for what the library is supposed to be then you're right - let's make it do something useful.

**Comment by martinklepsch** [comment]
Not sure if I understand what's the difference to sets with the approach we just agreed upon? 

My understanding is conj ing values will overwrite values 
- in a regular set based on the full value
- in ccsets based on a particular comparator

Also sorry for the brief communication, I'm on vacation/traveling and usually only have a phone to communicate.

**Comment by jmmk** [comment]
> My understanding is conj ing values will overwrite values
> - in a regular set based on the full value

If you see the above examples, this is true for ClojureScript but not true for Clojure. So it's somewhat an implementation detail but also could be a semantic detail (if the value is contained in the set, don't add it).
